const {chromium}=require('playwright');
const fs=require('fs');
const assert=require('assert');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const context=await browser.newContext({viewport:{width:1440,height:1120}});
 const page=await context.newPage(),errors=[],checks=[];const wait=page.waitForFunction.bind(page);page.waitForFunction=(fn,arg,opts={})=>wait(fn,arg,{polling:100,timeout:60000,...opts});
 page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{const raf=window.requestAnimationFrame;window.requestAnimationFrame=cb=>raf(t=>{if(!window.stopRendering)cb(t);else window.savedFrame=cb});window.observed=[];const WS=window.WebSocket;window.WebSocket=class extends WS{constructor(...args){super(...args);window.socket=this;this.addEventListener('message',e=>{window.latest=JSON.parse(e.data);if(window.latest.time>=4&&!window.observed[window.latest.trial])window.observed[window.latest.trial]=window.latest})}}});
 await page.goto('http://127.0.0.1:8501');
 await page.waitForFunction(()=>window.latest?.time>=2,{},{timeout:60000});
 const boot=await page.evaluate(()=>fetch('/api/bootstrap').then(r=>r.json()));
 assert.equal(boot.graph.provenance.neuron_count,23188);assert.equal(boot.graph.provenance.edge_count,1360021);assert.equal(boot.body_geometry.geoms.length,69);checks.push('Measured MANC and physical mesh bootstrap');
 const initial=await page.evaluate(()=>window.latest.body);
 await page.waitForFunction(()=>window.observed[1],{},{timeout:60000});
 const after=await page.evaluate(()=>window.observed[1]);
 assert.equal(after.prediction,1);assert.equal(after.input_body_id,10118);assert.notDeepEqual(initial.position,after.body.position);assert.notDeepEqual(initial.joint_angles,after.body.joint_angles);checks.push('Real decoded LEFT then RIGHT trials, moving physical body and joints');
 await page.evaluate(()=>window.stopRendering=true);await page.locator('#play').click();await page.waitForFunction(()=>!window.latest.running);
 const paused=await page.evaluate(()=>window.latest.body.physics_time);await page.waitForTimeout(450);assert.equal(paused,await page.evaluate(()=>window.latest.body.physics_time));checks.push('Pause freezes physics');
 await page.locator('#lesion').click();await page.waitForFunction(()=>window.latest.lesion);assert.equal(await page.evaluate(()=>window.latest.motors.L+window.latest.motors.R),0);
 await page.locator('#lesion').click();await page.waitForFunction(()=>!window.latest.lesion);checks.push('Synapse cut and restore');
 await page.locator('#truth-mode').click();await page.waitForFunction(()=>window.latest.mode==='truth');
 await page.locator('#decoded-mode').click();await page.waitForFunction(()=>window.latest.mode==='decoded');
 await page.locator('#speed').selectOption('2');await page.waitForTimeout(1000);console.log('SPEED',await page.evaluate(()=>({speed:window.latest.speed,value:document.querySelector('#speed').value})));await page.waitForFunction(()=>window.latest.speed===2);
 const previousTrial=await page.evaluate(()=>window.latest.trial);
 await page.locator('#next').click();await page.waitForFunction(t=>window.latest.trial===(t+1)%144,previousTrial);
 await page.locator('#reset').click();await page.waitForTimeout(500);console.log('RESET',await page.evaluate(()=>({trial:window.latest.trial,time:window.latest.body.physics_time,running:window.latest.running})),errors);await page.waitForFunction(()=>window.latest.trial===0&&window.latest.body.physics_time===0);checks.push('Both modes, speed, next and reset');
 await page.locator('#details').click();assert(await page.locator('#info-dialog').isVisible());await page.locator('#close-dialog').click();
 await page.evaluate(()=>{window.stopRendering=false;if(window.savedFrame)requestAnimationFrame(window.savedFrame)});await page.setViewportSize({width:390,height:844});await page.waitForTimeout(400);
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.screenshot({path:'mobile-preview.png',fullPage:true});checks.push('Details and mobile layout without horizontal overflow');
 assert.deepEqual(errors,[]);
 await context.close();await browser.close();
 fs.writeFileSync('data/validation/browser.json',JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({checks,errors}));
})().catch(e=>{console.error(e);process.exit(1)});
